name: PR Code Analysis

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PR Analysis Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          set -e  # Stop on error
          python pr_analyzer.py | tee analysis_result.txt  # Output to console & file
          echo "========== ANALYSIS RESULT =========="
          cat analysis_result.txt  # Display output for debugging
          echo "====================================="
          if grep -q "LLM_STATUS: FAIL" analysis_result.txt; then
            echo "Errors detected in PR. Failing the workflow."
            exit 1
          fi
